FROM nvidia/cuda:13.2.1-cudnn-runtime-ubuntu22.04

SHELL ["/bin/bash","-lc"]
ENV DEBIAN_FRONTEND=noninteractive
# ✅ 国内 pip 源，省流更稳
ENV PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple \
    PIP_TIMEOUT=120

# 基础依赖 + 用 apt 安装 GDCM（代替 python-gdcm）
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl wget git git-lfs \
    libgl1 libglib2.0-0 \
    python3-gdcm \
 && rm -rf /var/lib/apt/lists/*

# get gcc
RUN apt-get update && apt-get install -y \
	build-essential \ 
	cmake \
	ninja-build \
	gcc \
	git \
	g++ \
	libglib2.0-0 \
	libsm6 \
	libxext6 \
	libxrender-dev	\
 && rm -rf /var/lib/apt/lists/*


# get pip
RUN apt-get update && \
	apt-get install -y python3-pip
#RUN python3 -m pip install --upgrade pip

# enable git
RUN apt-get update && apt-get install git


# install pytorch
RUN pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu130


# 你的第三方库
COPY requirements.txt /env/requirements.txt
RUN pip install -U pip && pip install --no-cache-dir -r /env/requirements.txt

COPY requirements.txt /env/requirementsRadiomics.txt
RUN pip install -U pip && pip install --no-cache-dir -r /env/requirementsRadiomics.txt

COPY requirementsSAM.txt /env/requirementsSAM.txt
RUN pip install -U pip && pip install --no-cache-dir -r /env/requirementsSAM.txt

# GitHub installations:
RUN python3 -m pip install git+https://github.com/zhennongchen/CTProjector.git 

# 上面某个步骤好像会覆盖掉之前下载的pytorch（降版本），所以我们重新下载一个
RUN python3 -m pip uninstall -y torch torchvision nvidia-nccl-cu12 || true

# 2) 安装稳定版 cu130
RUN python3 -m pip install --no-cache-dir \
    torch==2.11.0+cu130 \
    torchvision==0.26.0+cu130 \
    --index-url https://download.pytorch.org/whl/cu130

# 3) 强制重装 NCCL cu13，修复可能的符号冲突/库缺失
RUN python3 -m pip install --no-cache-dir --force-reinstall \
    nvidia-nccl-cu13==2.28.9 \
    --index-url https://download.pytorch.org/whl/cu130




WORKDIR /workspace/ct_projector
EXPOSE 8888
# 直接内置好 Jupyter（和你之前的一样，token 用 mypw）
CMD ["bash","-lc","jupyter lab --allow-root --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token=mypw --notebook-dir=/workspace/ct_projector"]
